### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by FinalLody** [weimingtom/RipJavaHanzi#1]
Also it bing mei you shen me luan yong.

**Comment by weimingtom** [comment]
This tool is used for my company project. I have to decompile an android reader app and modify its code. ShakaApktool is enough, but I want to try to use jadx/jd for fun (compiling java code in Eclipse), so it's not meaningful.

**Comment by FinalLody** [comment]
I collect an android reader app ,maybe it will useful for you.
https://github.com/JMQCode/iBooks

**Comment by weimingtom** [comment]
Thanks, but I want a pdf and cebx reader with adding annotation functions, like Adobe pdf reader or Foxit reader for Android. It may be unsutable for me. Thank you very much, I like your recommended reader.

**Comment by FinalLody** [comment]
Best lucky for you.
